### PR TITLE
Apache Commons: collections4 and math3

### LINKED ISSUE #11: org.apache.commons:commons-collections4 - J2ObjC continuous build
Types that extend and augment the Java Collections Framework.

@netomi - FYI for you. This is to support translation of your Java library to Objective-C such that it can be used on iOS. This bug is specifically for testing this as part of a continuous build using Google's J2ObjC conversion tool.

@advayDev1 FYI

### PR DESCRIPTION
**Pull request by advayDev1**
Fixes #11

### CODE REVIEW

**Comment by brunobowden** [comment]
LGTM - this is the ideal example where there is minimal code for adding a new library. Commenting on PR so comment isn't lost.

**Comment by brunobowden** [comment]
Rebase this and I'll take another look.

**Comment by brunobowden** [comment]
@advayDev1 - we should get this rebased and merged

**Comment by advayDev1** [comment]
Well it translates and compiles.
Linkage fails with a very mysterious error.  Running it locally (same failure) shows that the error output has nothing but this:

```
 Static library archiver failed while archiving liborg.apache.commons-commons-math3-j2objc.a.
```

nothing else in any logs.  and the options.txt is not filled in by the time that fails, so nothing for me to reproduce.

Gradle source suggests this happens when you try to link an argument that is not a file https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativeBinariesIntegrationTest.groovy#L328

stumped - i'll have to tackle this later.

**Comment by iducool** [comment]
@advayDev1 I am running into the same error. Did you found any workaround?

**Comment by advayDev1** [comment]
Hi @iducool I don't work on this plugin anymore.  I would reach out to j2objc-discuss@googlegroups.com - but be forewarned this plugin is not officially supported by the Google team working on j2objc, and at this point is not maintained by anyone.

**Pull request closed without merging**
