### PR TITLE
Run against plugin v0.4.3-alpha; fixes #33

### LINKED ISSUE #33: Run tests against release plugin
We can do this with 2 environment variable values added to our travis matrix that control the classpath of the plugin jar (either from the local submodule or from plugins.gradle.org)

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by advayDev1** [comment]
@brunobowden ptal; reduces each build by 1.5-2 minutes

**Comment by brunobowden** [comment]
Given that we're referring to fixed library versions, I thought it would've been more helpful to get updates when we change the plugin? With this change, any breaking change in the plugin won't be discovered until it's published.

LGTM if you insist but I think we should look at this again.

**Comment by advayDev1** [comment]
The way it stands we can't catch such errors anyway (recall our discussion in #38).
I agree auto-updating would be nice, but I think we should add that as a separate branch.
When potential users visit this repo, they should see the state of our released plugin by default no?

not committing to continue discussion.

**Comment by advayDev1** [comment]
ping @brunobowden

**Comment by brunobowden** [comment]
LGTM

@advayDev1 - I would prefer a separate PR that did both build: release version and the j2objc-gradle HEAD.

**Comment by advayDev1** [comment]
This is discarded as it is old actually

**Pull request closed without merging**
